### ISSUE TITLE
Error in PATH  /nearyou/php/result.php

### ISSUE THREAD

**Issue by ccapudev** [thewhiteh4t/seeker#10]
Error de lectura XML:
no se encuentra el elemento raíz Ubicación:
https://6e9fa130.ngrok.io/nearyou/php/result.php
Número de línea 28, columna 1:

/nearyou/php/result.php:

$lat, 'lon' => $lon, 'acc' => $acc, 'alt' => $alt, 'dir' => $dir, 'spd' => $spd); $jdata = json_encode($data); $f = fopen('result.txt', 'w+'); fwrite($f, $jdata); fclose($f); } ?>

**Comment by thewhiteh4t** [comment]
which version are you using?

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.

**Comment by ccapudev** [comment]
Ubuntu 18.04 & Firefox 61.0.1 (64-bit)

**Comment by thewhiteh4t** [comment]
default path for apache folder for ubuntu and kali linux is 
`/var/www/html`
try this
`cd seeker/template`
`cp -r nearyou/ /var/www/html`
this will replace all template files, i had this problem and i have fixed this but i think you have old template files so replacing those files should fix this problem...please try and report

**Comment by ccapudev** [comment]
It does not solve it, but I tried it in a newly installed vbox and it worked.

**Comment by thewhiteh4t** [comment]
alright, i created it in ubuntu 18.04 and i encountered this error when i was testing it on termux, but i never got this error before the fix on ubuntu and kali linux, i dont know why you are getting it 

commit d864fda18fec09fcc2de9be729c9fc3ade0315e8

so should i close it now?

**Comment by ccapudev** [comment]
Yes, Close It :D

**Comment by benn1701** [comment]
I have this error in termux

**Comment by thewhiteh4t** [comment]
@benn1701 i tested with fresh termux install and its working fine
