### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by juniardoss** [thewhiteh4t/seeker#469]
**Describe the Error / Feature Request**

Discord webhook didn't work 
![vWZy](https://github.com/thewhiteh4t/seeker/assets/92383482/26830641-a148-4a9d-949e-a983548a5ec5)

**Comment by Resousse** [comment]
I don't know how discord webhook works, but I think they require mandatory parameters, that seeker is not able to provide..
I think the best would be : 
Seeker > HTTP Endpoint (PHP, Python, whatever) > Call Discord API
The component in the middle would be in charge to receive seeker data and to forward it to discord giving mandatory params

**Comment by thewhiteh4t** [comment]
@juniardoss I am working on discord webhook support, it will be available soon

**Comment by thewhiteh4t** [comment]
@juniardoss i have added support for discord webhook, please try it out, I will be fine tuning it more but it should be working right now

**Comment by juniardoss** [comment]
> @juniardoss i have added support for discord webhook, please try it out, I will be fine tuning it more but it should be working right now

Didn't work still showing `[-] Unable to reach the webhook endpoint, ensure it listens on a POST method and unauthenfied`

![snippet (1)](https://github.com/thewhiteh4t/seeker/assets/92383482/302aaab7-d76d-4b93-b6f7-ea175330cd05)

**Comment by thewhiteh4t** [comment]
@juniardoss you need to update, 
```
cd seeker
git pull
```

**Comment by juniardoss** [comment]
> @juniardoss you need to update,
> 
> ```
> cd seeker
> git pull
> ```

![Screenshot 2023-08-30 092255](https://github.com/thewhiteh4t/seeker/assets/92383482/4d89535c-51bd-45b8-8ff6-14dc7dba0638)

thanks it worked!

**Comment by tawsiefsofi** [comment]
Zphisher is not working in Termux!
